name: pywi-dev
channels:
  - jdhp
  - conda-forge
dependencies:
  - docutils
  - pep8
  - pytest
  - pytest-cov
  - setuptools
  - sphinx
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinxcontrib
  - sphinxcontrib-websupport
  - numba
  - numpy
  - scipy
  - scikit-image
  - pillow
  - astropy
  - matplotlib
  - numba
  - pip:
      - pytest_runner
